spring:
  application:
    name: rpg-member-user
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      rate: 1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cainiao:123456@81.71.36.134:40000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
server:
  port: 43000
