spring:
  application:
    name: rpg-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cloud-gateway
          uri: lb://rpg-cloud-oauth2
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=2
        - id: member-user
          uri: lb://rpg-member-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cainiao:123456@127.0.0.1:40000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
    prefer-ip-address: true
server:
  port: 42000